version: "3.9"

services:
  client:
    container_name: wallet
    image: wallet
    build: 
      context: . #путь до докерфайла
      dockerfile: Dockerfile #Сам файл
      target: wallet #этап FROM в Dockerfile 
    restart: always
    ports:
      - 8080:8080
    networks:
      local-network: 
        ipv4_address: 172.16.0.10
    links: # сокращенные именя для подключения
      - exchanger
      - redis
      - db
    depends_on: #ожидаем запуска остальных сервисов
      - exchanger
      - redis
      - db
  exchanger:
    container_name: autstore
    image: autstore
    build: 
      context: . 
      dockerfile: Dockerfile 
      target: autstore 
    restart: always
    networks:
      local-network: 
        ipv4_address: 172.16.0.11
    links:
      - db
    depends_on:
      - db
  db:
    container_name: autstore-db
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pkg/postgre_init.sql:/docker-entrypoint-initdb.d/1-init.sql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      local-network: 
        ipv4_address: 172.16.0.12
  redis:
    container_name: redis-server
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_REPLICATION_MODE: master
    networks:
      local-network: 
        ipv4_address: 172.16.0.13
    # volumes: 
    #   - redis_cache:/data
  

volumes:
  postgres_data:
  # redis_cache:

networks:
  local-network:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
    