env: "local" #local, dev, prod
http_server: 
  address: "localhost"
  port: ":8080"
  timeout: 5s 
  idle_timeout: 120s
grpc_remote_server: 
  address: "exchanger"
  port: 8081
redis_remote_server: 
  address: "redis"
  port: 6379
storage:
  host: "db"
  port: 5432
  database: "score"
  user: "user"
  pass: "puser"

